[workspace]
resolver = "3"
members = [
    "crates/umbral-lexer",
    "crates/umbral-parser",
    "crates/umbral-runtime",
    "crates/umbral-interpreter",
    "crates/umbral-cli",
    "crates/umbral-repl"
]