[package]
name = "umbral-repl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
umbral-interpreter = { path = "../umbral-interpreter" }
rustyline = "14.0"
tokio = { version = "1", features = ["full"] }
