[package]
name = "umbral-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
umbral-parser = { path = "../umbral-parser" }
umbral-lexer = { path = "../umbral-lexer" }
rand = "0.8"
serde_json = "1.0"
