[package]
name = "umbral-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
umbral-lexer = { path = "../umbral-lexer" }
umbral-parser = { path = "../umbral-parser" }
umbral-runtime = { path = "../umbral-runtime" }
