[package]
name = "umbral-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
umbral-lexer = { path = "../umbral-lexer" }
umbral-parser = { path = "../umbral-parser" }
umbral-runtime = { path = "../umbral-runtime" }